package guru.springboot.mssc.beer.order.service.domain;

public enum BeerOrderStatusEnum {
  NEW, VALIDATED, VALIDATION_PENDING , VALIDATION_EXCEPTION,
  ALLOCATION_PENDING, ALLOCATED, ALLOCATION_EXCEPTION, READY, PICKED_UP,
  DELIVERED, DELIVERY_EXCEPTION, PENDING_INVENTORY
}
